apiVersion: v1
kind: Pod
metadata:
  name: log-debug
  namespace: monitoring
spec:
  # serviceAccountName: fluent-bit
  containers:
    - name: debug
      image: busybox:latest
      command:
        - sleep
        - "3600"
      securityContext:
        runAsUser: 0 # Run as root to ensure access to all log files
      volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: podlogs
          mountPath: /var/log/pods
          readOnly: true
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: podlogs
      hostPath:
        path: /var/log/pods
