apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: fluent-bit
#   namespace: monitoring
#
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: fluent-bit-role
# rules:
#   - apiGroups: [""]
#     resources:
#       - pods
#       - namespaces
#     verbs: ["get", "list", "watch"]
#
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: fluent-bit-role-binding
# subjects:
#   - kind: ServiceAccount
#     name: fluent-bit
#     namespace: monitoring
# roleRef:
#   kind: ClusterRole
#   name: fluent-bit-role
#   apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      # serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.2.0
          args:
            - -c
            - /fluent-bit/etc/fluent-bit.conf
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    debug
        Parsers_File parsers.conf

    [INPUT]
        Name             tail
        Path             /var/log/containers/*monitoring*.log
        Parser           docker,regex
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        DB               /fluent-bit/tail.db
        Read_from_Head   true
    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log        On
        Merge_Log_Key    log_processed
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off
    [OUTPUT]
        Name         stdout
        Match        *
        Format       json_lines
        Json_date_key    timestamp
        Json_date_format iso8601
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As json log

    [PARSER]
        Name        regex
        Format      regex
        Regex       ^(?<time>[^ ]*) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
