apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Pod
metadata:
  name: example-golang-app
  namespace: monitoring
  labels:
    app: example-golang-app
spec:
  containers:
    - name: my-example
      image: go-prometheus-demo:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-golang-app
  namespace: monitoring
spec:
  selector:
    app: example-golang-app
  ports:
    - port: 8081
      targetPort: 8080
      name: metrics
---

