apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-demo
  namespace: monitoring
  labels:
    app: stress-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-demo
  template:
    metadata:
      labels:
        app: stress-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: stress-test
          image: prom-cpu-mem-hog:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: stress-demo
  namespace: monitoring
spec:
  selector:
    app: stress-demo
  ports:
    - port: 8000
      targetPort: 8000
      name: metrics
