name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: #enabled manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: '1.24.2'

      - name: Check Go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v -buildvcs=false ./...

      - name: Test
        run: go test -v ./...
