apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-prometheus-demo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 2s
